### ISSUE TITLE
urllib2.URLError

### ISSUE THREAD

**Issue by lonly197** [baidu/bigflow#36]
# Environment

OS: Centos7.2
Spark: HDP-2.1
Hadoop: HDP-2.7

I have set SPARK_HOME, HADOOP_HOME and BIGFLOW_PYTHON_HOME.

# Description

I have error after running `print pipeline.read(input.TextFile("hdfs://localhost:8020/data/test/new.txt")).get()`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bigflow/ptype.py", line 87, in get
    if not self._is_readable():
  File "bigflow/ptype.py", line 127, in _is_readable
    return requests.is_node_cached(self._pipeline.id(), self._node.id())
  File "bigflow/rpc/requests.py", line 68, in _wrapper
    result, status = func(*args, **kw)
  File "bigflow/rpc/requests.py", line 318, in is_node_cached
    response = _service.request(request, "is_node_cached")
  File "bigflow/rpc/service.py", line 89, in request
    response = urllib2.urlopen(req, request_json, 365 * 24 * 60 * 60)
  File "/opt/bigflow/python_runtime/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/bigflow/python_runtime/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/bigflow/python_runtime/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/bigflow/python_runtime/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/bigflow/python_runtime/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/opt/bigflow/python_runtime/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```
I tried `hdfs://data/test/new.txt` and `/data/test/new.txt`, but still not work.

**Comment by advancedxy** [comment]
Hi, can you paste your  bigflow_backend.${pid}.log or share a link to the bigflow_backend.${pid}.log?

The backend log location should be in the first lines of your program output. 

From your stack trace, it looks like that the backend server doesn't startup or has been shutdown for unknown reason.

**Comment by acmol** [comment]
I'll have a try within a docker mirror on centos 7.2, wait 4 me.

**Comment by acmol** [comment]
As we communicated in wechat, @lonly197  has discovered the reason was an config error. So, this issue could be closed.
